let profilepic=document.getElementById('profile');
let inputfile=document.getElementById('input-file');
let imgs=document.getElementById('i1');
inputfile.onchange=function(){
profilepic.src=URL.createObjectURL(inputfile.files[0]);
}
 function myimge(){
   var name=document.getElementById('nam').value;
   var age=document.getElementById('ag').value;
   var dob=document.getElementById('do').value;
    var email=document.getElementById('emai').value;
     var phone=document.getElementById('pno').value;
      var adress=document.getElementById('ad').value;
   var nation=document.getElementById('nation').value;
    var maria=document.getElementById('marrage').value;
     var comname=document.getElementById('cname').value;
      var jobtite=document.getElementById('jtitle').value;
       var years =document.getElementById('years').value;
        var award=document.getElementById('awards').value;
         var jdescription=document.getElementById('jobdesc').value;
         var objectiv=document.getElementById('objdesc').value;
          var t1=document.getElementById('text').value;
           var t2=document.getElementById('text1').value;
            var t3=document.getElementById('text2').value;
             var n1=document.getElementById('text0').value;
             var n2=document.getElementById('text21').value;
    var n3=document.getElementById('text22').value;
   var h1=document.getElementById('text31').value;
  var h2=document.getElementById('text32').value;
 var h3=document.getElementById('text33').value;
 var scool=document.getElementById('sname').value;
                var cg1=document.getElementById('cgpa').value;
     var ad1=document.getElementById( 'adress').value;
  var collage=document.getElementById('cname').value;
   var cg2=document.getElementById('cgpa2').value;
  var ad2=document.getElementById('adress1').value;
   var project=document.getElementById('pname').value;
  var domain=document.getElementById('domain').value;
 var projectdesc=document.getElementById('pdesc').value;
var win=window.open("","","width=1000,height=1000");
win.document.write('<html lang="en" dir="ltr">');
win.document.write(  '<head>');
win.document.write(    '<meta charset="utf-8">');
  win.document.write(  '<link rel="stylesheet" href="resume.css">');
win.document.write(   ' <title></title>');
win.document.write(  '</head>');
  win.document.write('<body>');
  win.document.write(' <h1>RESUME</h1>');
win.document.write('<div class="main">');
  win.document.write('<span id="f1">');
  win.document.write( ' <img src='+profilepic.src+' alt="" id="i1">');
  win.document.write('  <hr id="s1" >');
win.document.write('<h4 id="contact">CONTACT DETAILS</h4>');
win.document.write('<li >&#9193; Email &nbsp &nbsp&nbsp&nbsp&nbsp:-'+email+'</li>');
win.document.write('<li>&#9193;Phone no&nbsp :-'+phone+'</li>');
win.document.write('<li>&#9193;Address&nbsp&nbsp&nbsp&nbsp:-'+adress+'</li>');
win.document.write('<h4 id="contact">PERSONAL DETAILS</h4>');
win.document.write('<li >&#9193; Nationality:-&nbsp &nbsp&nbsp&nbsp&nbsp:-'+nation+'</li>');
win.document.write('<li>&#9193;Marial Status:-&nbsp :-'+maria+'</li>');
win.document.write('<h4 id="contact">SKILLS</h4>');
win.document.write('<dl class="">');
win.document.write('<dt>TECHNICAL</dt>');
win.document.write('<dd>1.'+t1+'</dd>');
win.document.write('<dd>2.'+t2+'</dd>');
win.document.write('<dd>3.'+t3+'</dd>');
win.document.write('<dt>Non-Technical</dt>');
win.document.write('<dd>1.'+n1+'</dd>');
win.document.write('<dd>2.'+n2+'</dd>');
win.document.write('<dd>3.'+n3+'</dd>');
win.document.write('</dl>');
win.document.write('<h4 id="contact">Hobbies</h4>');
win.document.write('<li >1.'+h1+'</li>');
win.document.write('<li>2.'+h2+'</li>');
win.document.write('<li>3.'+h3+'</li>');
win.document.write(  '</span>');
  win.document.write('<span id="f2">');
  win.document.write(  '<hr id="s2">');
    win.document.write( '<h4>NAME:-'+name+'</h4>');
  win.document.write(   '<h3 id="age">AGE:-'+age+'</h3>');
      win.document.write('<h3 id="dob">DOB:-'+dob+'</h3>');
      win.document.write('<h3 class="obj">Objective</h3>');
    win.document.write(  '<hr>');
    win.document.write(  '<p>'+objectiv+'</p>');
    win.document.write(  '<h3 class="obj"> Work Experience</h3>');
    win.document.write(  '<hr>');
    win.document.write(  '<ul>');
      win.document.write(  '<li>Company Nmae&nbsp:-'+comname+'</li>');
    win.document.write(    '<li>Job title&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:-'+jobtite+'</li>');
    win.document.write(    '<li>NO.Years&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:-'+years+'</li>');
    win.document.write(    '<li>Awards&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:-'+award+'</li>');
      win.document.write( ' <li>description&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:-'+jdescription+'</li>');
    win.document.write(  '</ul>');
    win.document.write( ' <h3 class="obj">Education</h3>');
  win.document.write(   ' <hr>');
  win.document.write(  '<table border="1" cellspacing="0" cellpadding="10px"width="100%">');
  win.document.write(    '<caption><b>SCHOOL</b></caption>');
  win.document.write(   ' <th>NAME</th>');
  win.document.write(  '  <th>Address</th>');
  win.document.write( '   <th>C.G.P.A</th>');
  win.document.write('    <tr>');
win.document.write('<td>'+scool+'</td>');
win.document.write('<td>'+ad1+'</td>');
  win.document.write('<td>'+cg1+'</td>');
    win.document.write( ' </tr>');
  win.document.write(  '</table>');
  win.document.write(  '<table border="1" cellspacing="0" cellpadding="10px" width="100%">');
    win.document.write(  '<caption><b>Collage</b></caption>');
    win.document.write(  '<th>NAME</th>');
  win.document.write(    '<th>Address</th>');
  win.document.write(   ' <th>C.G.P.A</th>');
    win.document.write('  <tr>');
win.document.write('<td>'+collage+'</td>');
win.document.write('<td>'+ad2+'</td>');
win.document.write('<td>'+cg2+'</td>');
win.document.write(     ' </tr>');
win.document.write(    '</table>');
  win.document.write(    '<hr>');
    win.document.write(  '    <h3 class="obj">Projects</h3>');
  win.document.write(    '<ul>');
  win.document.write(    '  <li>Name &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:-'+project+'</li>');
    win.document.write( '   <li>Domain&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:-'+domain+'</li>');
    win.document.write('    <li>Discription:-'+projectdesc+'</li>');
  win.document.write('    </ul>');
win.document.write( ' </span>');
win.document.write('</div>');
win.document.write('<button type="button" name="button" onclick="myfunction()">print</button>');
win.document.write('<script  src="res.js"></script>');
win.document.write( ' </body>');
win.document.write('</html>');
}
